git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never

os:
  editCommand: 'nvim'

customCommands:
  - key: "Z"
    command: "npx cz"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
